"""Curated trending hotel & attraction data for East Java cities."""

from datetime import date

CITIES = ["surabaya", "sidoarjo", "mojokerto", "pasuruan"]

PLATFORMS = ["Traveloka", "Booking.com", "Agoda", "Trip.com", "Klook", "Tiket.com"]

HOTELS: dict[str, list[dict]] = {
    "surabaya": [
        {
            "name": "Platinum Hotel Tunjungan",
            "stars": 4,
            "rating": 9.2,
            "reviews": 1757,
            "price": "Rp 988.867",
            "platform": "Traveloka",
            "highlight": "#1 popularitas Traveloka Surabaya. View lantai 20, lokasi strategis.",
            "url": "https://www.traveloka.com/id-id/hotel/indonesia/platinum-hotel-tunjungan-surabaya-9000000987493",
        },
        {
            "name": "Four Points by Sheraton Pakuwon Indah",
            "stars": 4,
            "rating": 9.0,
            "reviews": 2979,
            "price": "Rp 800.000+",
            "platform": "Traveloka",
            "highlight": "2.979 review! Show cooking restaurant, pool, gym.",
            "url": "https://www.traveloka.com/id-id/hotel/indonesia/city/surabaya-103570",
        },
        {
            "name": "Sheraton Surabaya Hotel & Towers",
            "stars": 5,
            "rating": 9.5,
            "reviews": 291,
            "price": "Rp 1.200.000+",
            "platform": "Booking.com",
            "highlight": "Lokasi terbaik Embong Malang. Airport shuttle. Pool, spa.",
            "url": "https://www.booking.com/hotel/id/sheraton-surabaya.html",
        },
        {
            "name": "JW Marriott Hotel Surabaya",
            "stars": 5,
            "rating": 8.8,
            "reviews": 1294,
            "price": "Rp 1.500.000+",
            "platform": "Booking.com",
            "highlight": "Hotel mewah 5-star. 1.294 review TripAdvisor. Brand terpercaya.",
            "url": "https://www.booking.com/hotel/id/jw-marriott-surabaya.html",
        },
        {
            "name": "Vasa Hotel Surabaya",
            "stars": 5,
            "rating": 9.0,
            "reviews": 210,
            "price": "Rp 900.000+",
            "platform": "Trip.com",
            "highlight": "Desain modern, clean rooms. Populer business traveler.",
            "url": "https://www.trip.com/hotels/sukomanunggal-hotel-detail-6401210/vasa-hotel-surabaya/",
        },
        {
            "name": "Bumi Surabaya City Resort",
            "stars": 5,
            "rating": 8.5,
            "reviews": 83,
            "price": "Rp 800.000+",
            "platform": "Trip.com",
            "highlight": "Resort di tengah kota. Taman luas, colonial heritage.",
            "url": "https://id.trip.com/hotels/surabaya-hotel-detail-2197118/bumi-surabaya-city-resort/",
        },
        {
            "name": "ARTOTEL TS Suites Surabaya",
            "stars": 4,
            "rating": 8.8,
            "reviews": 500,
            "price": "Rp 700.000+",
            "platform": "Traveloka",
            "highlight": "Desain arty unik. Top staycation pick Traveloka.",
            "url": "https://www.traveloka.com/id-id/hotel/indonesia/city/surabaya-103570",
        },
        {
            "name": "Hotel Majapahit MGallery",
            "stars": 5,
            "rating": 9.0,
            "reviews": 800,
            "price": "Rp 1.200.000+",
            "platform": "Booking.com",
            "highlight": "Heritage legendaris sejak 1910. Arsitektur kolonial Belanda.",
            "url": "https://www.booking.com/hotel/id/majapahit-surabaya.html",
        },
        {
            "name": "Shangri-La Surabaya",
            "stars": 5,
            "rating": 9.2,
            "reviews": 600,
            "price": "Rp 1.300.000+",
            "platform": "Agoda",
            "highlight": "Hotel mewah, pool besar, spa premium. Area bisnis utama.",
            "url": "https://www.agoda.com/city/surabaya-id.html",
        },
        {
            "name": "Swiss-Belhotel Darmo",
            "stars": 4,
            "rating": 8.5,
            "reviews": 400,
            "price": "Rp 600.000+",
            "platform": "Agoda",
            "highlight": "Area Darmo strategis. Pool, restaurant. Value for money.",
            "url": "https://www.agoda.com/city/surabaya-id.html",
        },
    ],
    "sidoarjo": [
        {
            "name": "Favehotel Sidoarjo",
            "stars": 3,
            "rating": 9.6,
            "reviews": 50,
            "price": "Rp 330.000",
            "platform": "Trip.com",
            "highlight": "Rating TERTINGGI Trip.com! Bersih, modern, staf ramah.",
            "url": "https://www.trip.com/hotels/sidoarjo-hotel-detail-35090811/favehotel-sidoarjo/",
        },
        {
            "name": "Aston Sidoarjo City Hotel",
            "stars": 4,
            "rating": 8.4,
            "reviews": 117,
            "price": "Rp 500.000+",
            "platform": "Booking.com",
            "highlight": "Hotel bintang 4. Conference center. Terbaik bisnis/MICE.",
            "url": "https://www.booking.com/city/id/sidoarjo.html",
        },
        {
            "name": "Swiss-Belinn Airport Surabaya",
            "stars": 3,
            "rating": 8.1,
            "reviews": 417,
            "price": "Rp 400.000+",
            "platform": "Booking.com",
            "highlight": "417 review! Dekat bandara Juanda. Best value transit.",
            "url": "https://www.booking.com/city/id/sidoarjo.html",
        },
        {
            "name": "Ndalem Kraton Hotel",
            "stars": 3,
            "rating": 9.0,
            "reviews": 6,
            "price": "Rp 250.000+",
            "platform": "Booking.com",
            "highlight": "Water playground anak. Pool outdoor. Cocok keluarga.",
            "url": "https://www.booking.com/city/id/sidoarjo.html",
        },
        {
            "name": "Neo+ Waru Sidoarjo by Aston",
            "stars": 3,
            "rating": 9.0,
            "reviews": 30,
            "price": "Rp 350.000+",
            "platform": "Trip.com",
            "highlight": "Transit hotel populer. Parkir luas, refill air gratis.",
            "url": "https://in.trip.com/hotels/sidoarjo-hotels-list-60305/",
        },
        {
            "name": "Premier Place Surabaya Airport",
            "stars": 3,
            "rating": 8.0,
            "reviews": 100,
            "price": "Rp 400.000+",
            "platform": "Booking.com",
            "highlight": "Pool, WiFi, dekat bandara. Business traveler.",
            "url": "https://www.booking.com/city/id/sidoarjo.html",
        },
    ],
    "mojokerto": [
        {
            "name": "Aston Mojokerto Hotel & Conference Center",
            "stars": 4,
            "rating": 9.5,
            "reviews": 106,
            "price": "Rp 530.000",
            "platform": "Trip.com",
            "highlight": "Top-rated semua platform. Pool, gym, conference center.",
            "url": "https://www.booking.com/hotel/id/aston-mojokerto-amp-conference-center.id.html",
        },
        {
            "name": "Ayola Sunrise Hotel Mojokerto",
            "stars": 3,
            "rating": 9.1,
            "reviews": 200,
            "price": "Rp 378.780",
            "platform": "Trip.com",
            "highlight": "Di atas mall, pemandangan kota. 470+ mention 'mall' di review.",
            "url": "https://id.trip.com/hotels/mojokerto-hotels-list-63082/",
        },
        {
            "name": "Lynn Hotel Mojokerto",
            "stars": 3,
            "rating": 9.7,
            "reviews": 30,
            "price": "Rp 378.780",
            "platform": "Trip.com",
            "highlight": "Rating tertinggi Trip.com! Hotel baru, pool, cocok keluarga.",
            "url": "https://id.trip.com/hotels/mojokerto-hotels-list-63082/",
        },
        {
            "name": "Grand Whiz Hotel Trawas",
            "stars": 3,
            "rating": 9.2,
            "reviews": 5763,
            "price": "Rp 511.504",
            "platform": "Traveloka",
            "highlight": "5.763 review! Kawasan wisata Trawas. Pool, view pegunungan.",
            "url": "https://www.traveloka.com/id-id/hotel/indonesia/city/mojokerto-103393",
        },
        {
            "name": "Box City Hotel Mojokerto",
            "stars": 3,
            "rating": 8.8,
            "reviews": 24,
            "price": "Rp 300.000",
            "platform": "Booking.com",
            "highlight": "Hotel baru, dekat stasiun. Bersih, staf ramah. Budget-friendly.",
            "url": "https://www.booking.com/city/id/mojokerto.html",
        },
        {
            "name": "Bobocabin Pacet Mojokerto",
            "stars": 3,
            "rating": 9.3,
            "reviews": 40,
            "price": "Rp 300.000+",
            "platform": "Trip.com",
            "highlight": "Glamping/cabin modern. Instagram-worthy. Populer anak muda.",
            "url": "https://my.trip.com/hotels/mojokerto-regency-hotels-list-731573/",
        },
        {
            "name": "Royal Hotel and Villas Trawas",
            "stars": 3,
            "rating": 7.8,
            "reviews": 18,
            "price": "Rp 220.000-3jt",
            "platform": "Trip.com",
            "highlight": "Villa view alam. Cocok keluarga/grup besar.",
            "url": "https://my.trip.com/hotels/mojokerto-regency-hotels-list-731573/",
        },
    ],
    "pasuruan": [
        {
            "name": "Royal Senyiur Hotel (Prigen)",
            "stars": 4,
            "rating": 9.2,
            "reviews": 2990,
            "price": "Rp 550.375+",
            "platform": "Traveloka",
            "highlight": "#1 popularitas Traveloka Pasuruan. Kids friendly, pool, rooftop bar.",
            "url": "https://www.traveloka.com/id-id/hotel/indonesia/city/pasuruan-103262",
        },
        {
            "name": "Baobab Safari Resort (Prigen)",
            "stars": 4,
            "rating": 8.6,
            "reviews": 4029,
            "price": "Rp 800.000+",
            "platform": "Traveloka",
            "highlight": "4.029 review! Satu lokasi Taman Safari. Diskon tiket safari.",
            "url": "https://www.traveloka.com/id-id/hotel/indonesia/city/pasuruan-103262",
        },
        {
            "name": "Surya Hotel & Cottages Prigen",
            "stars": 3,
            "rating": 8.9,
            "reviews": 4621,
            "price": "Rp 662.608",
            "platform": "Traveloka",
            "highlight": "4.621 review terbanyak! Cottage + pool + view pegunungan.",
            "url": "https://www.traveloka.com/id-id/hotel/indonesia/city/pasuruan-103262",
        },
        {
            "name": "Inna Tretes Hotel & Resort",
            "stars": 3,
            "rating": 8.6,
            "reviews": 3863,
            "price": "Rp 383.677",
            "platform": "Traveloka",
            "highlight": "3.863 review. Resort klasik, taman luas, view Gunung Arjuna.",
            "url": "https://www.traveloka.com/id-id/hotel/indonesia/city/pasuruan-103262",
        },
        {
            "name": "Tretes Raya Hotel",
            "stars": 3,
            "rating": 8.2,
            "reviews": 2574,
            "price": "Rp 300.000+",
            "platform": "Traveloka",
            "highlight": "2.574 review. Arsitektur kolonial Belanda. Pool + waterslide.",
            "url": "https://www.traveloka.com/id-id/hotel/indonesia/city/pasuruan-103262",
        },
        {
            "name": "Rauda Living Space Syariah",
            "stars": 3,
            "rating": 9.5,
            "reviews": 6,
            "price": "Rp 270.000",
            "platform": "Booking.com",
            "highlight": "Rating tertinggi Booking! Taman, WiFi gratis. Syariah-friendly.",
            "url": "https://www.booking.com/city/id/pasuruan.html",
        },
        {
            "name": "Sinergi Hotel Tretes",
            "stars": 3,
            "rating": 8.6,
            "reviews": 316,
            "price": "Rp 300.000+",
            "platform": "Agoda",
            "highlight": "Kawasan wisata Tretes. View pegunungan.",
            "url": "https://www.agoda.com/sinergi-hotel-tretes/hotel/pasuruan-id.html",
        },
    ],
}

ATTRACTIONS: dict[str, list[dict]] = {
    "surabaya": [
        {
            "name": "Tour Gunung Bromo (dari Surabaya)",
            "price": "Rp 370rb-1.6jt",
            "platform": "Klook",
            "booked": "6K+",
            "highlight": "TERLARIS #1! Sunrise tour paling dicari. Private & sharing.",
            "url": "https://www.klook.com/destination/c337-surabaya/1-things-to-do/",
        },
        {
            "name": "Kebun Binatang Surabaya (KBS)",
            "price": "Rp 15.000-30.000",
            "platform": "Traveloka",
            "booked": "Populer",
            "highlight": "Kebun binatang terbesar & tertua di Asia Tenggara.",
            "url": "https://www.traveloka.com/id-id/activities/indonesia/city/surabaya-103570",
        },
        {
            "name": "Tour Bromo & Ijen Multiday",
            "price": "Rp 1jt-1.6jt",
            "platform": "Klook",
            "booked": "1K+",
            "highlight": "Sharing & private tour. Multi speaking guide.",
            "url": "https://www.klook.com/destination/c337-surabaya/1-things-to-do/",
        },
        {
            "name": "House of Sampoerna",
            "price": "Gratis",
            "platform": "Klook",
            "booked": "Populer",
            "highlight": "Museum rokok legendaris + cafe. Free walking tour Surabaya Lama.",
            "url": "https://www.klook.com/destination/c337-surabaya/1-things-to-do/",
        },
        {
            "name": "Monumen Kapal Selam (Monkasel)",
            "price": "Rp 15.000",
            "platform": "Traveloka",
            "booked": "Populer",
            "highlight": "Museum kapal selam asli. Ikon wisata sejarah Surabaya.",
            "url": "https://www.traveloka.com/id-id/activities/indonesia/city/surabaya-103570",
        },
        {
            "name": "Tugu Pahlawan",
            "price": "Rp 5.000-10.000",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Monumen ikonik 10 November. Museum sejarah perang kemerdekaan.",
            "url": "",
        },
        {
            "name": "Tirta Ayu Spa Kayoon",
            "price": "Rp 120.000",
            "platform": "Klook",
            "booked": "300+",
            "highlight": "Spa experience populer wisatawan asing.",
            "url": "https://www.klook.com/destination/c337-surabaya/1-things-to-do/",
        },
        {
            "name": "Kenjeran Park / Atlantis Land",
            "price": "Rp 25.000-50.000",
            "platform": "Traveloka",
            "booked": "Populer",
            "highlight": "Taman rekreasi tepi pantai. Patung Buddha raksasa.",
            "url": "https://www.traveloka.com/id-id/activities/indonesia/city/surabaya-103570",
        },
    ],
    "sidoarjo": [
        {
            "name": "Asri Park",
            "price": "Rp 15.000-25.000",
            "platform": "Traveloka",
            "booked": "Populer",
            "highlight": "Taman wisata keluarga Sukodono. Wahana bermain, spot foto.",
            "url": "https://www.traveloka.com/en-id/activities/indonesia/product/asri-park-location-5409701799901",
        },
        {
            "name": "Delta Fishing",
            "price": "Rp 10.000-15.000",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Wisata keluarga #1 Sidoarjo. Kolam pancing, lesehan, wahana.",
            "url": "",
        },
        {
            "name": "Sun City Waterpark",
            "price": "Rp 35.000-50.000",
            "platform": "Tiket.com",
            "booked": "Populer",
            "highlight": "Waterpark tengah kota. Seluncuran, kolam arus, waterboom.",
            "url": "",
        },
        {
            "name": "Kampoeng Batik Jetis",
            "price": "Gratis",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Wisata budaya batik. Belajar membatik. Bangunan lawas instagrammable.",
            "url": "",
        },
        {
            "name": "Candi Pari",
            "price": "Rp 5.000-10.000",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Candi Majapahit abad 14. Wisata sejarah unik.",
            "url": "",
        },
        {
            "name": "Pasar Ikan Sidoarjo",
            "price": "Gratis",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Pusat kuliner seafood. Terkenal bandeng & udang Sidoarjo.",
            "url": "",
        },
    ],
    "mojokerto": [
        {
            "name": "Claket Adventure Park",
            "price": "Rp 15.000-50.000",
            "platform": "Traveloka",
            "booked": "Populer",
            "highlight": "Wahana adrenalin + wisata alam. High-rope, flying fox.",
            "url": "https://www.traveloka.com/id-id/explore/activities/claket-adventure-park-mojokerto-ta/1001795",
        },
        {
            "name": "Museum Trowulan (Majapahit)",
            "price": "Rp 4.000-7.000",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Museum arkeologi warisan Majapahit. Koleksi emas, keramik, relief.",
            "url": "",
        },
        {
            "name": "Candi Tikus",
            "price": "Rp 5.000",
            "platform": "Traveloka",
            "booked": "Populer",
            "highlight": "Candi peninggalan Majapahit. Sangat instagrammable.",
            "url": "",
        },
        {
            "name": "Trowulan Majapahit Temple Tour",
            "price": "Varies",
            "platform": "Klook",
            "booked": "Populer",
            "highlight": "Private day tour situs-situs Majapahit.",
            "url": "",
        },
        {
            "name": "Air Terjun Dlundung (Trawas)",
            "price": "Rp 10.000-20.000",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Air terjun kawasan Trawas. Sejuk, cocok hiking ringan.",
            "url": "",
        },
        {
            "name": "Pacet Mini Park",
            "price": "Rp 15.000-25.000",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Wahana outbound + mini zoo. Populer weekend keluarga.",
            "url": "",
        },
    ],
    "pasuruan": [
        {
            "name": "Taman Safari Indonesia 2 (Prigen)",
            "price": "Rp 95.000-250.000",
            "platform": "Traveloka",
            "booked": "50+ (Klook)",
            "highlight": "ATRAKSI #1 PASURUAN! Safari drive, animal show, waterpark.",
            "url": "https://www.traveloka.com/en-en/activities/indonesia/product/taman-safari-indonesia-2-jatim-tickets-prigen-2000334012402",
        },
        {
            "name": "Air Terjun Kakek Bodo",
            "price": "Rp 18.000-28.000",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Tinggi 40m. Daya tarik internasional. TWA Tretes.",
            "url": "",
        },
        {
            "name": "Air Terjun Putuk Truno",
            "price": "Rp 18.000-28.000",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "Air terjun ikonik Pasuruan. Dekat area hotel Tretes.",
            "url": "",
        },
        {
            "name": "Taman Wisata Alam (TWA) Tretes",
            "price": "Rp 18.000 (domestik)",
            "platform": "Lokal",
            "booked": "Populer",
            "highlight": "10 hektar lereng Gunung Arjuna. Hutan pinus, fauna langka.",
            "url": "",
        },
        {
            "name": "Gunung Bromo (akses via Pasuruan)",
            "price": "Rp 30.000-220.000",
            "platform": "Klook",
            "booked": "6K+",
            "highlight": "Sunrise iconic. Banyak tour dari Pasuruan. High season terus.",
            "url": "https://www.klook.com/destination/c337-surabaya/1-things-to-do/",
        },
        {
            "name": "Cimory Dairyland",
            "price": "Rp 50.000",
            "platform": "Traveloka",
            "booked": "Populer",
            "highlight": "Wisata edukatif peternakan sapi. Populer keluarga.",
            "url": "",
        },
    ],
}


def get_city_display(city: str) -> str:
    return {
        "surabaya": "Surabaya",
        "sidoarjo": "Sidoarjo",
        "mojokerto": "Mojokerto",
        "pasuruan": "Pasuruan",
    }.get(city, city.title())


def get_today_str() -> str:
    return date.today().strftime("%d %B %Y")
